1 new Exception("Something unexpected happened");